# Dependencies
highlighter: rouge

# Setup
title:            vivencio2 
tagline:          'Developers Thought Process'
description:      'My Technical Journey'
url:              "https://vivenc.io"
baseurl:          /

author:
  name:           'Jayr Anes'
  url:            https://twitter.com/vivencio2tweets

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/vivencio2

theme: jekyll-theme-minimal